// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://secjpvnypjwgwwaucwrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlY2pwdm55cGp3Z3d3YXVjd3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwODA0MDQsImV4cCI6MjA3NzY1NjQwNH0.pxtK7_APa1XUioyLDBW-7znMdUmzBX_8yntyZo5w1jM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});